### ISSUE TITLE
I'm getting a white screen when I open Chamilo Mobile?

### ISSUE THREAD

**Issue by shabsshab** [nosolored/chamilo-mobile#5]
I have sucesfully build Android APK for chamilo mobile app but when i install apk in mobile and open getting a white screen.
please assist what would be the issue

**Comment by nosolored** [comment]
Hello,
We can not know what is the problem. We need more information: Chamilo version, Android version...
Could you provide debug info from Google Chrome code inspector?

**Comment by shabsshab** [comment]
I have used the code from here : https://github.com/nosolored/chamilo-mobile and build APK.
My chamilo LMS is 1.11.12 latest version.

iam talking about only in chamilo mobile app which is APK, so cannot get debug from browser

**Comment by danieldocumentos** [comment]
Después de arreglar las rutas pues ustedes en config.xml en la etiqueta de plataforma redireccionan a una carpeta que no proporcionan "res", al modificar esa carencia la pantalla sale blanca. Intenté probar la aplicación con ionic serve pero me dice que no es el archivo de ionic. asi que la configuro pero no deja lanzarla, no puedo depurarla.

**Comment by nosolored** [comment]
Tienes razón Daniel, hemos vuelto a subir el proyecto, verifica que tienes todas las carpetas
